

app:
  service:
    routesApiUrl: 'https://services-api.ryanair.com/locate/3/routes'
    schedulesApiUrl: 'https://services-api.ryanair.com/timtbl/3/schedules/{departure}/{arrival}/years/{year}/months/{month}'
server:
  servlet:
    context-path: /flights-info
